### ISSUE TITLE
first `flutter start` + new phone == Unexpected failure parsing device information from adb output

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#101]
This is the very first time I enabled developer mode on my phone, and the very first time I tried pushing a flutter demo onto the phone. I apparently wasn't fast enough allowing the USB debugging, and even though I did tap the checkbox and tapped allow, the `flutter start` command errored like this:

```
Seths-iMac:my_app sethladd$ flutter start
Downloading Sky Snapshot from the cloud, one moment please...
Downloading Sky Shell from the cloud, one moment please...
warning: Unexpected failure parsing device information from adb output:
84B7N15A07007628       unauthorized usb:437387264X
Please report a bug at http://flutter.io/
severe: Unable to run application - no connected devices.
```

Maybe we can either wait longer, or check for this error and interpret it as "Please allow USB debugging and try again" ?

**Comment by sethladd** [comment]
I should note, on the second `flutter start`, everything worked!

**Comment by devoncarew** [comment]
The regexs live on and around here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/device.dart#L525

We have logic for checking for `unauthorized` - it may either be bad or not expecting that exact pattern.

**Comment by abarth** [comment]
Yeah, it's not matching the "usb:437387264X" part at the end

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/565

**Comment by sethladd** [comment]
Thanks for the quick fix!
