### ISSUE TITLE
Requesting API docs for dart:ui

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#102]
Sitting here with my son :) trying to build a game with Flutter. I think we want basic dart:ui but I'm not actually sure what that is, to be honest. I see we're generating docs for package:flutter but I didn't see docs for dart:ui.

Are they hosted somewhere? Related, are there any other dart: libraries that I would want to check out?

Thanks!

**Comment by abarth** [comment]
> Are they hosted somewhere?

Nope.

> I think we want basic dart:ui but I'm not actually sure what that is, to be honest.

The `dart:ui` library is (intentionally) very low-level.  You can see some examples of using it directly in this directory:

https://github.com/flutter/flutter/tree/master/examples/raw

Depending on what you're doing, you might want to try the flutter_sprites package, which is intended for folks writing games.

**Comment by abarth** [comment]
You can see an extensive flutter_sprites example at https://github.com/flutter/game

**Comment by sethladd** [comment]
> The dart:ui library is (intentionally) very low-level

Good point. I've convinced myself I don't need to see it :)

> Depending on what you're doing, you might want to try the flutter_sprites package

Which we're going to check out right now. Thanks!

Going to close this request for now, but I suspect we'll want to generate these docs soon enough.

Thanks!
