### ISSUE TITLE
Implement custom search engine for Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#109]
So we can search across all our API docs, flutter.io docs, and anything else useful for developers.

**Comment by sethladd** [comment]
cc @appsforartists

**Comment by appsforartists** [comment]
Related: #108

**Comment by sethladd** [comment]
Taking a look at this.

**Comment by sethladd** [comment]
Current cut:

![screen shot 2015-12-09 at 11 45 10 am](https://cloud.githubusercontent.com/assets/5479/11696671/5bf0ebbe-9e6a-11e5-993f-cd3efc2889a3.png)
