### ISSUE TITLE
Update naming, sky --> flutter

### ISSUE THREAD

**Issue by Scorpiion** [flutter/flutter.github.io#16]
See the getting started guide for example:
http://flutter.io/getting-started/

**Comment by abarth** [comment]
Yes, the next step is to rename the Dart package from `sky` to `flutter`.

**Comment by Scorpiion** [comment]
Ah, I missed that the current flutter package on pub might be a placeholder. But yeah, when that's done this follows as you said.

**Comment by abarth** [comment]
It's probably the right time to rename the package.  I've been holding off on it because it's relatively disruptive to developers, but it doesn't get easier as time goes on.

**Comment by Scorpiion** [comment]
I understand, I think it's the right time now too. 

It does becomes a little bit misleading too for newcomers when the name change is not 100% completed, so you might as well complete the process. Most people (for whom it matters) should know about the name change by now.

**Comment by abarth** [comment]
Ok, I've renamed `package:sky` to `package:flutter`.  We still reference `sky_tool` in some places because we haven't finished the migration from Python to Dart for that code yet.

**Comment by Scorpiion** [comment]
:+1:

**Comment by abarth** [comment]
We've switched the docs over to using `flutter` instead of `sky_tool`.  I'm going to declare victory on this issue.
