### ISSUE TITLE
Tutorial needs assets: search.png and menu.png

### ISSUE THREAD

**Issue by afandria** [flutter/flutter.github.io#17]
IIRC, this refers to the `MyButton` tutorial. Instructions for where to place these images are needed too.

Link to the [flutter-dev thread]
(https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/flutter-dev/OtTY7lbv78A/0n3RIHVhCAAJ)

**Comment by abarth** [comment]
Thanks!

**Comment by abarth** [comment]
The tutorial no longer refers to these assets.  Instead, it uses material design icons that developers will actually have.
