### ISSUE TITLE
analysis issues w/ the snippets

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter.github.io#23]
Related to #22 - the build failure can be seen here: https://travis-ci.org/flutter/flutter.github.io#L271.

```
[warning] The method 'debugDumpRenderTree' is not defined for the class 'FlutterBinding' at example/rendering_md_1.dart, line 401.
[warning] Undefined class 'ShrinkWrapWidth' at example/tutorial_md_5.dart, line 220.

[warning] The named parameter 'child' is not defined at example/tutorial_md_5.dart, line 220.
[warning] The named parameter 'child' is not defined at example/tutorial_md_6.dart, line 299.
[warning] The named parameter 'child' is not defined at example/tutorial_md_7.dart, line 417.
```

@abarth @Hixie

**Comment by Hixie** [comment]
The debugDumpRenderTree needs to import rendering.dart.
ShrinkWrapWidth should be renamed IntrinsicWidth.

Not sure what the other three are, which tutorial examples are these?

**Comment by devoncarew** [comment]
I try to keep the file name similar the the line number the same. So, they're all from `tutorial.md`, lines 220, 299, and 417.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter.github.io/pull/24 for the tutorial ones. Which file is example/rendering.md?

**Comment by Hixie** [comment]
Hm, actually that PR didn't make Travis entirely happy. I made some mistakes. Unfortunately I can't figure out how to edit the PR on the Web. Should be useful to explain what needs to happen though.

**Comment by abarth** [comment]
https://github.com/flutter/flutter.github.io/blob/master/rendering.md

**Comment by devoncarew** [comment]
If you have it cloned locally, you can also run `dart tool/extract.dart`, which will create (and re-create) dart files from the markdown snippets. That's a preview of what the bot's doing.

**Comment by Hixie** [comment]
I did the PR by directly editing the file on Github's Web site. :-)
