### ISSUE TITLE
Start hosting complete API docs for Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#27]
Looks like https://domokit.github.io/docs/sky/ is out of date. It's still using the sky name and hosted under domokit.

Should we have a Travis process or other automated process to build the API docs for Flutter?

**Comment by sethladd** [comment]
cc @devoncarew any thoughts?

(changing to bug because we're linking to these docs from flutter.io)

**Comment by abarth** [comment]
Yeah, we should move it somewhere sensible and automate the process for updating it.

**Comment by devoncarew** [comment]
Creating them on travis is pretty easy. I get stuck on the auth issues of having travis push to a github repo (https://github.com/flutter/flutter.github.io).

**Comment by sethladd** [comment]
Can we bump this up?

* URL is on old domain (domokit): https://domokit.github.io/docs/sky/
* Still using the Sky name
* Not up to date (0.0.7 is what we've doc'ed, but we've published 0.0.13)
* Not complete (it doesn't document the entire core libs provided by flutter)

Thanks!

**Comment by sethladd** [comment]
FWIW, dartdocs.org is now generating docs for the Flutter package: http://www.dartdocs.org/documentation/flutter/0.0.13/index.html

However, that's not the complete API offered by Flutter. So I think we still need to how our own api.flutter.io. Discussion welcome!

**Comment by devoncarew** [comment]
I have a handle on the auth issues now(https://github.com/google/grinder.dart/pull/303); I think this is doable.

**Comment by sethladd** [comment]
We're doing a lot of this now.
