### ISSUE TITLE
Example from Basic Widgets does not run

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#34]
In http://flutter.io/tutorial/

![screen shot 2015-10-29 at 1 54 35 pm](https://cloud.githubusercontent.com/assets/5479/10831756/a55d2d9e-7e44-11e5-97bd-973011ca57cc.png)

**Comment by sethladd** [comment]
Hi @Hixie if you have some spare cycles, wondering if you could help take a look at this. Should the example from the Basic Widgets tutorial through this exception? Thanks!

**Comment by abarth** [comment]
I think the problem is that we need a flutter.yaml file that references this asset now that we don't have an HTTP server.

**Comment by abarth** [comment]
If you add the `--http` argument to the `start` command, does it work?

**Comment by Hixie** [comment]
The immediate problem is that `DefaultAssetBundle.of(context))` returned null for some reason.

**Comment by abarth** [comment]
Maybe there's no material app and therefore no default bundle?

**Comment by Hixie** [comment]
Yeah, there's no MaterialApp in the tutorial code.

**Comment by sethladd** [comment]
Thanks. I'll give it a try and if it works, will update the tutorial.
