### ISSUE TITLE
Specify which version of Dart we need, in Getting Started

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#63]

**Comment by sethladd** [comment]
@abarth our website says to get --devel, but I think our new policy is that you can install flutter with a stable channel SDK. Shall I change to say we support 1.12.2 or greater?

**Comment by abarth** [comment]
1.12.2 or greater should work currently.

**Comment by sethladd** [comment]
Addressed with https://github.com/flutter/flutter.github.io/pull/64
