### ISSUE TITLE
add a sample flutter.yaml file to the tutorial

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter.github.io#71]
Any icon mentioned here: https://github.com/flutter/flutter.github.io/blob/master/tutorial.md should be referenced in the flutter.yaml.

**Comment by sethladd** [comment]
We might want to consider matching the tutorial to the starter app that we generate for users. We'll still need to explain what the flutter.yaml file is, but we won't have to ask the user to create it during the tutorial :)

**Comment by sethladd** [comment]
Looks like the tutorial now has a flutter.yaml reference/example.
