### ISSUE TITLE
Specify exact OS version(s) and API level(s) that Flutter supports

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#73]
Crib from https://source.android.com/source/build-numbers.html

We mention this in Getting Start and the FAQ, if not other places.

**Comment by devoncarew** [comment]
Right now it's Jelly Bean, v16, 4.1.x and above.

**Comment by sethladd** [comment]
Addressed in https://github.com/flutter/flutter.github.io/pull/80
