### ISSUE TITLE
adjust title color?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter.github.io#8]
The Flutter site and the API docs have different primary colors.

<img width="193" alt="screen shot 2015-09-26 at 4 14 04 pm" src="https://cloud.githubusercontent.com/assets/1269969/10120312/c02baf00-6469-11e5-96f3-5969dc45bd82.png">

<img width="150" alt="screen shot 2015-09-26 at 4 14 14 pm" src="https://cloud.githubusercontent.com/assets/1269969/10120311/c02a2932-6469-11e5-98b6-ee89cede5caa.png">

Are we committed to the current Flutter color? I'd like to make the colors the same - either the Flutter color or a new third color.

**Comment by abarth** [comment]
I'd prefer to adopt the purple and make the docs match the site.  The blue in the docs is just the default given by dartdoc.

**Comment by devoncarew** [comment]
(fixed by https://github.com/flutter/engine/pull/1375)
