### ISSUE TITLE
Better explanations about installation of adb for linux users

### ISSUE THREAD

**Issue by a14n** [flutter/flutter.github.io#87]
On _Ubuntu 14.04 (64b TLS)_ the _adb_ provided via _apt_ is too old.
So I followed the link provided in [getting started](http://flutter.io/getting-started/#setting-up-your-android-device) and downloaded the SDK Tools but it's not obvious what should be done next.

It could be worth to mention somewhere :

* launch `tools/android`
* install (only?) _Android SDK Platfrom-tools_
* add `platform-tools/` to your PATH
* check that `adb devices -l` lists your device

On this last item I got an misleading error _adb: No such file or directory_ (or something like that). I figured out that it was because I needed to install _lib32stdc++6_ package (Actually there's a section _Troubleshooting Ubuntu_ on the [Installing the Stand-alone SDK Tools](https://developer.android.com/sdk/installing/index.html?pkg=tools) that mentions this package but I did not read it because it was under a section _Here are the steps to install Java_ ) . It would also be nice to mention that issue too.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by sethladd** [comment]
If you'd like to submit a patch for review, that would be appreciated. Since you recently went through the flow, I assume you can document all the steps?

**Comment by a14n** [comment]
Fixed by #103
